server:
  port: 19090
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ENC(cxgWkJC78u4XgQ9PgwAQDwHJ6+wJnfIpYIhyv6vNihYUdpnfsaDOXIa8MgN1vUJ1)
    username: admin
    password: ENC(CY/t4Xu2Au2cNweK2LrnRQ==)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate.orm.jdbc.bind: trace
jasypt:
  key: ${jasypt_key}