server:
  port: 19090
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ENC(S26VUNMwMQGrekf6b2QILhs01dR7iu2BTNkPi2Q2YmlsyLop8XrRifeYQL0KpQRp)
    username: admin
    password: ENC(CY/t4Xu2Au2cNweK2LrnRQ==)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jasypt:
  key: ${jasypt_key}